name: av_foundation
description: Framework for working with time-based audiovisual media on iOS.
version: 0.0.1
homepage: 'https://github.com/bparrishMines/penguin/tree/master/packages/av_foundation'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  reference: ^0.4.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  reference_generator:
    path: ../reference_generator

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AvFoundationPlugin
