# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `pub run build_runner build`
targets:
  $default:
    sources:
      include:
        - tool/**
    builders:
      json_serializable:
        generate_for:
          - lib/src/plugin.dart
        options:
          any_map: true
          checked: true
          field_rename: snake
