name: test_plugin
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  test_plugin_platform_interface:
    path: ../test_plugin_platform_interface
  penguin:
    git:
      url: git://github.com/bparrishMines/penguin.git
      path: penguin
      ref: penguin4
  reference:
    path: ../reference

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.test_plugin
    pluginClass: TestPlugin
