name: ios_avfoundation_example
description: Demonstrates how to use the ios_avfoundation plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  ios_avfoundation:
    path: ../
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
