name: reference
description: Reduce plugin maintenance burden for plugins that have to maintain platform object instances in memory.
version: 0.4.1+1
homepage: https://github.com/bparrishMines/penguin/tree/master/packages/reference

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  ffi: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  plugin:
    platforms:
      android:
        package: github.penguin.reference
        pluginClass: ReferencePlugin
      ios:
        pluginClass: ReferencePlugin
