name: penguin_usage
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  penguin:
    path: ../penguin/
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.6.7
  penguin_generator:
    path: ../penguin_generator/
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.penguin_usage
    pluginClass: PenguinUsagePlugin
