name: gen_api_impls
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/bparrishMines/penguin

environment:
  sdk: '>=3.0.0-147.0.dev <4.0.0'

dependencies:
  path: ^1.8.3
  recase:  4.1.0
  simple_ast:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/simple_ast

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
