name: penguin_camera
description: Provides a platform-agnostic interface for accessing cameras camera features.
version: 0.0.1
homepage: https://github.com/bparrishMines/penguin/tree/master/packages/penguin_camera

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  av_foundation: ^0.0.1
  android_hardware: ^0.0.1
  android_media: ^0.0.1
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: ^2.0.1
  permission_handler: ^8.0.0+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

