name: simple_ast_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^2.4.0
  build: ^2.3.0
  path: ^1.8.0
  simple_ast:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/simple_ast
  source_gen: ^1.2.2

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.1.10
  build_test: ^2.1.5
  lints: ^1.0.0
  test: ^1.16.0
