name: simple_ast_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  build: ^2.3.1
  path: ^1.8.3
  simple_ast:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/simple_ast
  source_gen: ^1.2.7

dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.3.3
  build_test: ^2.1.6
  lints: ^2.0.1
  test: ^1.23.1
