include: package:lint/analysis_options_package.yaml
analyzer:
  exclude: [lib/src/camera.g.dart']

linter:
  rules:
    avoid_classes_with_only_static_members: false
    cast_nullable_to_non_nullable: false
    # public_member_api_docs: true

