#builders:
#  ast_builder:
#    import: 'package:reference_generator/builder.dart'
#    builder_factories: ['dartBuilder']
#    build_extensions:
#      .dart:
#      - .g.dart
#    build_to: source
#    auto_apply: none
