builders:
  referenceAstBuilder:
    import: 'package:reference_generator/builder.dart'
    builder_factories: ['referenceAstBuilder']
    build_extensions:
      .dart:
      - .reference_ast
    build_to: source
    auto_apply: dependents
