name: av_foundation_example
description: Demonstrates how to use the av_foundation plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  av_foundation:
    path: ../
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  permission_handler: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
