targets:
  $default:
    builders:
      penguin_generator|penguin:
        enabled: false

builders:
  read_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["readBuilder"]
    build_extensions: {".dart": [".penguin.g.info"]}
    build_to: cache
    runs_before: [":write_builder"]
    auto_apply: dependents

  write_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["writeBuilder"]
    build_extensions: {r"$lib$": ["android.penguin.g.dart", "ios.penguin.g.dart", "ChannelGenerated.java"]}
    build_to: source
    auto_apply: dependents
