name: penguin_generator
description: A new flutter package project.
version: 1.0.0
author: Jorge Coca <jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/todo_reporter.dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dart_style: ^1.3.0
  json_annotation: ^3.0.0
  recase: 2.0.1
  pubspec_parse: ^0.1.5
  build: ^1.1.6
  source_gen: ^0.9.4+4
  glob: ^1.1.7
  penguin:
    git:
      url: git://github.com/bparrishMines/penguin.git
      path: penguin
  
dev_dependencies:
  json_serializable: ^3.2.0
  build_test: ^0.10.8
  build_runner: ^1.6.7
  test: ^1.8.0
