name: ios_avfoundation
description: A Flutter plugin that provides access to the AVFoundation dependency on iOS.
version: 0.0.1
author: Brandon Parrish
homepage: 'https://github.com/bparrishMines/penguin/tree/master/packages/ios_avfoundation'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  reference:
    path: ../reference

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  lint: ^1.5.1
  reference_generator:
    path: ../reference_generator

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosAvfoundationPlugin