name: penguin_plugin
description: Penguin Utilities
version: 0.0.1
author:
homepage: 'eoifj'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  uuid: 2.0.4
  penguin:
    git:
      url: git://github.com/bparrishMines/penguin.git
      path: penguin
      ref: penguin4
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.1
  penguin_generator:
    git:
      url: git://github.com/bparrishMines/penguin.git
      path: penguin_generator
      ref: reference_counting

flutter:
  plugin:
    androidPackage: plugins.penguin.penguin_plugin
    pluginClass: PenguinPlugin
