name: penguin_camera
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  reference: ^0.2.0-beta
  device_info: 2.0.0-nullsafety.2
  plugin_platform_interface: ^1.1.0-nullsafety.1
  flutter_plugin_android_lifecycle: ^2.0.0-nullsafety.2
  flutter:
    sdk: flutter

dev_dependencies:
  reference_generator:
    path: ../reference_generator
  build_runner: ^1.10.13
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: bparrishMines.penguin.penguin_camera
        pluginClass: PenguinCameraPlugin
      ios:
        pluginClass: PenguinCameraPlugin
