name: reference
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: 'woefij'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  uuid: 2.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.reference
        pluginClass: ReferencePlugin
      ios:
        pluginClass: ReferencePlugin
