name: reference
description: Reduce plugin maintenance burden for plugins that have to maintain platform object instances in memory.
version: 0.2.0-beta
homepage: https://github.com/bparrishMines/penguin/tree/master/reference

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: github.penguin.reference
        pluginClass: ReferencePlugin
      ios:
        pluginClass: ReferencePlugin
