name: reference
description: A Flutter plugin for creating a plugin API with the Reference Pair model.
version: 0.0.1
homepage: https://github.com/bparrishMines/penguin/tree/master/reference

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  uuid: ^2.0.4
  quiver: ^2.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: github.penguin.reference
        pluginClass: ReferencePlugin
      ios:
        pluginClass: ReferencePlugin
