name: reference
description: Reduce plugin maintenance burden for plugins that have to maintain platform object instances in memory.
version: 0.1.0
homepage: https://github.com/bparrishMines/penguin/tree/master/reference

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  uuid: ^2.0.4
  quiver: ^2.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: 4.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: github.penguin.reference
        pluginClass: ReferencePlugin
      ios:
        pluginClass: ReferencePlugin
