name: simple_ast
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-202.0.dev <3.0.0'

dependencies:
  json_annotation: ^4.4.0

dev_dependencies:
  build: ^2.3.0
  build_config: ^1.0.0
  build_runner: ^2.1.10
  build_test: ^2.1.5
  json_serializable: ^6.1.6
  lints: ^1.0.0
