name: code_template_processor
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.3.0
  colorize: ^3.0.0
  file: ^6.1.2
  path: ^1.8.0
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.0
  mockito: ^5.1.0
  test: ^1.20.1
