builders:
  info_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["infoBuilder"]
    build_extensions: {".dart": [".info"]}
    build_to: cache
    runs_before: [":platform_builder", ":dart_builder"]
    auto_apply: root_package

  platform_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["platformBuilder"]
    build_extensions: {r"$lib$": ["ChannelGenerated.java", "ChannelHandler+Generated.h", "ChannelHandler+Generated.m"]}
    build_to: source
    auto_apply: root_package

  dart_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["dartBuilder"]
    build_extensions: {".info": [".android.penguin.g.dart", ".ios.penguin.g.dart"]}
    build_to: source
    auto_apply: root_package
