name: android_hardware
description: Provides support for Android hardware features, such as the camera and other sensors.
version: 0.0.1
homepage: https://github.com/bparrishMines/penguin/tree/master/packages/android_hardware

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  reference: ^0.4.3

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  reference_generator:
    path: ../reference_generator

flutter:
  plugin:
    platforms:
      android:
        package: dev.penguin.android_hardware
        pluginClass: AndroidHardwarePlugin
