name: Labeler

on:
  pull_request:
    branches:
      - main

jobs:
  label:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/labler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

