name: todo_reporter_generator
description: A new flutter package project.
version: 1.0.0
author: Jorge Coca <jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/todo_reporter.dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: ^1.1.6
  source_gen: ^0.9.4+4
  penguin:
    path: ../penguin/
  
dev_dependencies:
  build_test: ^0.10.8
  build_runner: ^1.6.7
  test: ^1.6.8