name: penguin_android_camera_example
description: Demonstrates how to use the penguin_android_camera plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  permission_handler: ^5.0.1+1
  flutter:
    sdk: flutter
  penguin_android_camera:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
