targets:
  $default:
    builders:
      penguin_generator|penguin:
        enabled: true

builders:
  read_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["readBuilder"]
    build_extensions: {".dart": [".penguin.g.info"]}
    auto_apply: dependents
    runs_before: [':write_builder']
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  write_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["writeBuilder"]
    build_extensions: {"$lib$": ["nada"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
