targets:
  $default:
    builders:
      penguin_generator|penguin:
        enabled: true

builders:
  todo_reporter:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["classBuilder"]
    build_extensions: {".dart": [".class.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]