targets:
  $default:
    builders:
      penguin_generator|penguin:
        enabled: false

builders:
  read_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["readBuilder"]
    build_extensions: {".dart": [".penguin.g.info"]}
    build_to: cache
    auto_apply: dependents
    applies_builders: [":write_builder"]

  write_builder:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["writeBuilder"]
    build_extensions: {r"$lib$": ["nada"]}
