targets:
  $default:
    builders:
      penguin_generator|penguin:
        enabled: true

builders:
  dart:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["dartBuilder"]
    build_extensions: {r".dart": [".penguin.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  android:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["androidBuilder"]
    build_extensions: {r".dart": [".java"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
