targets:
  $default:
    builders:
      penguin_generator|penguin:
        enabled: true

builders:
  dart:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["dartBuilder"]
    build_extensions: {".dart": [".penguin.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  android:
    target: ":penguin_generator"
    import: "package:penguin_generator/builder.dart"
    builder_factories: ["androidBuilder"]
    build_extensions: {".dart": [".android"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder", ":android_move"]

post_process_builders:
  android_move:
    import: "package:penguin_generator/builder.dart"
    builder_factory: "androidMoveBuilder"
    input_extensions: [".android"]
