name: reference_generator
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  recase: ^4.0.0
  args: ^2.1.0
  source_gen: ^1.0.1
  json_annotation: ^4.0.1
  reference:
    path: ../reference
#    git:
#      url: https://github.com/bparrishMines/penguin.git
#      ref: gen_update
#      path: packages/reference
  build: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  json_serializable: ^4.1.3
  build_test: ^2.1.0
  build_config: ^1.0.0
  build_runner: ^2.0.4
  pedantic: ^1.11.0
  test: ^1.17.5
