name: penguin
version: 0.0.1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  args: ^1.5.2
  path: ^1.6.2
  yaml: ^2.1.16
  code_builder: ^3.2.0
  dart_style: ^1.2.9
  json_annotation: ^2.4.0
  checked_yaml: ^1.0.1
  pubspec_parse: ^0.1.4
  pub_semver: ^1.4.2

dev_dependencies:
  json_serializable: ^3.0.0
  build_runner: ^1.0.0
  test: ^1.6.5

executables:
  penguin:
