name: example
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  penguin:
    path: ../penguin/

dev_dependencies:
  build_runner: ^1.6.7
  flutter_test:
    sdk: flutter
  penguin_generator:
    path: ../penguin_generator/
