name: reference_example
description: A new flutter plugin project.
version: 0.0.1
homepage: "none"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  reference:
    git:
      url: https://github.com/bparrishMines/penguin.git
      ref: gen_update
      path: packages/reference
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  reference_generator:
    path: ../reference_generator
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.reference_example
        pluginClass: ReferenceExamplePlugin
      ios:
        pluginClass: ReferenceExamplePlugin
