name: reference_example
description: A new flutter plugin project.
version: 0.0.1
author: "none"
homepage: "none"
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  reference: 0.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  reference_generator:
    path: ../reference_generator


flutter:
  plugin:
    platforms:
      android:
        package: com.example.reference_example
        pluginClass: ReferenceExamplePlugin
      ios:
        pluginClass: ReferenceExamplePlugin
