name: reference_example
description: A new flutter plugin project.
version: 0.0.1
author: "none"
homepage: "none"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  reference:
    path: ../reference
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.reference_example
        pluginClass: ReferenceExamplePlugin
      ios:
        pluginClass: ReferenceExamplePlugin
