name: Android Media Tests

on:
  pull_request:
    paths:
      - packages/android_media/**
      - .github/workflows/android_media.yaml
  push:
    branches:
      - master

env:
  PLUGIN_DIR: packages/android_media

jobs:
  verify_dart:
    name: Dart Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
#      - name: Dart Unit Tests
#        run: |
#          cd $PLUGIN_DIR
#          flutter test
      - name: Dart Publish
        run: |
          cd $PLUGIN_DIR
          flutter pub publish --dry-run
      - name: Dart Analyze
        run: |
          cd $PLUGIN_DIR
          flutter analyze
      - name: Dart Documentation
        run: |
          cd $PLUGIN_DIR
          flutter pub global activate dartdoc
          flutter pub global run dartdoc --no-generate-docs --errors='broken-link,unresolved-doc-reference' --verbose-warnings

  verify_android:
    name: Android Tests
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Android Build Test
        run: |
          cd $PLUGIN_DIR/example
          flutter build apk
      - name: Android Unit Tests
        run: |
          cd $PLUGIN_DIR/example/android
          ./gradlew test
