name: AVFoundation Plugin Tests

on:
  pull_request:
    paths:
      - packages/av_foundation/**
      - .github/workflows/av_foundation.yaml
  push:
    branches:
      - master

env:
  PLUGIN_DIR: packages/av_foundation

jobs:
  verify_dart:
    name: Dart Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
#      - name: Dart Unit Tests
#        run: |
#          cd $PLUGIN_DIR
#          flutter test
      - name: Dart Publish
        run: |
          cd $PLUGIN_DIR
          flutter pub publish --dry-run
      - name: Dart Analyze
        run: |
          cd $PLUGIN_DIR
          flutter analyze
      - name: Dart Documentation
        run: |
          cd $PLUGIN_DIR
          flutter pub global activate dartdoc
          flutter pub global run dartdoc --no-generate-docs --errors='broken-link,unresolved-doc-reference' --verbose-warnings

  verify_ios:
    name: Ios Tests
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Ios Build Test
        run: |
         cd $PLUGIN_DIR/example
         flutter build ios --simulator --no-codesign
      - name: Ios Unit Tests
        run: |
         cd $PLUGIN_DIR/example/ios
         xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test

