name: Ios AVFoundation Tests

on:
  pull_request:
    paths:
      - packages/ios_avfoundation/**
      - .github/workflows/ios_avfoundation.yaml
  push:
    branches:
      - master

env:
  PLUGIN_DIR: packages/ios_avfoundation

jobs:
  verify_dart:
    name: Dart Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Dart Unit Tests
        run: |
          cd $PLUGIN_DIR
          flutter test
      - name: Dart Analyze
        run: |
          cd $PLUGIN_DIR
          flutter analyze

  verify_ios:
    name: Ios Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Ios Build Test
        run: |
         cd $PLUGIN_DIR/example
         flutter build ios --simulator --no-codesign
      - name: Ios Unit Tests
        run: |
         cd $PLUGIN_DIR/example/ios
         xcodebuild -project Runner.xcodeproj -scheme Runner -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test

