name: A workflow for my Hello World file
on: push 

env:
  PLUGIN_DIR: packages/reference

jobs:
  build:
    name: Something something
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Dart Unit Tests
        run: |
          cd $PLUGIN_DIR
          flutter test
      - name: Ios Unit Tests
        run: |
          cd $PLUGIN_DIR/ios
          pod lib lint --verbose
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
      - name: Android Build Test
        run: |
          cd $PLUGIN_DIR/example
          flutter build apk
      - name: Ios Build Test
        run: |
         cd $PLUGIN_DIR/example
         flutter build ios --no-codesign
